const DATA={
      OpenAI:{pos:61,neu:27,neg:12,score:68,mentions:7842,eng:'1.8M',driver:'Product launch',risk:'Low',themes:['model updates','developer tools','pricing','safety','ChatGPT'],alerts:['Positive spike after product announcement','Developer discussions rising 31%','Support complaints below threshold']},
      Tesla:{pos:44,neu:30,neg:26,score:31,mentions:11620,eng:'2.4M',driver:'Earnings debate',risk:'Medium',themes:['deliveries','autopilot','stock price','charging','competition'],alerts:['Negative comments increasing in investor segment','High engagement on pricing debate','News mentions above weekly average']},
      Bitcoin:{pos:52,neu:24,neg:24,score:42,mentions:22340,eng:'4.7M',driver:'Price movement',risk:'Medium',themes:['ETF flows','halving','macro','whales','regulation'],alerts:['Volume 2.1× above baseline','Neutral news coverage shifting positive','Risk: scam keywords rising']},
      Apple:{pos:49,neu:38,neg:13,score:55,mentions:9140,eng:'1.2M',driver:'Product reviews',risk:'Low',themes:['iPhone','privacy','ecosystem','AI features','design'],alerts:['Reviews remain mostly stable','Privacy mentions high confidence','Negative sentiment concentrated in pricing']},
      '#AI':{pos:58,neu:29,neg:13,score:64,mentions:18730,eng:'3.5M',driver:'Industry adoption',risk:'Low',themes:['automation','jobs','agents','education','startups'],alerts:['Creator engagement up 44%','Education debate trending','Policy terms increasing']},
      NVIDIA:{pos:66,neu:22,neg:12,score:72,mentions:14870,eng:'2.9M',driver:'GPU demand',risk:'Low',themes:['AI chips','earnings','data centers','supply','CUDA'],alerts:['Bullish investor posts rising','Supply-chain topic gaining speed','Negative comments below baseline']}
    };
    const ctx={trend:null,source:null};
    const $=id=>document.getElementById(id);
    function nums(topic){const d=DATA[topic]||DATA.OpenAI;return d}
    function genTrend(d){let labels=[],pos=[],neu=[],neg=[];for(let i=23;i>=0;i--){labels.push((i===0?'now':`-${i}h`));let wave=Math.sin(i/3)*5;pos.push(Math.max(20,Math.min(80,d.pos+wave+Math.random()*4-2)));neu.push(Math.max(10,Math.min(50,d.neu-wave/2+Math.random()*3-1.5)));neg.push(Math.max(5,Math.min(45,d.neg-wave/3+Math.random()*3-1.5)));}return{labels,pos,neu,neg}}
    function renderCharts(d){const t=genTrend(d);if(ctx.trend)ctx.trend.destroy();ctx.trend=new Chart($('trendChart'),{type:'line',data:{labels:t.labels,datasets:[{label:'Positive',data:t.pos,borderColor:'#16a34a',backgroundColor:'rgba(22,163,74,.09)',fill:true,tension:.38,borderWidth:2,pointRadius:0},{label:'Neutral',data:t.neu,borderColor:'#0891b2',backgroundColor:'rgba(8,145,178,.05)',fill:true,tension:.38,borderWidth:2,pointRadius:0},{label:'Negative',data:t.neg,borderColor:'#dc2626',backgroundColor:'rgba(220,38,38,.06)',fill:true,tension:.38,borderWidth:2,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}},scales:{y:{beginAtZero:true,max:100,ticks:{callback:v=>v+'%'},grid:{color:'#edf2f7'}},x:{grid:{display:false}}}}});
    if(ctx.source)ctx.source.destroy();ctx.source=new Chart($('sourceChart'),{type:'doughnut',data:{labels:['X','Reddit','News','YouTube','Forums'],datasets:[{data:[42,22,17,12,7],backgroundColor:['#2563eb','#7c3aed','#16a34a','#d97706','#0891b2'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}}});}
    function render(topic){const d=nums(topic);$('topicTitle').textContent=topic;$('mentions').textContent=d.mentions.toLocaleString();$('positive').textContent=d.pos+'%';$('neutral').textContent=d.neu+'%';$('negative').textContent=d.neg+'%';$('engagement').textContent=d.eng;$('netScore').textContent=(d.score>0?'+':'')+d.score;$('driver').textContent=d.driver;$('risk').textContent=d.risk;$('scoreRing').style.background=`conic-gradient(#16a34a 0 ${d.pos}%, #e5e7eb ${d.pos}% 100%)`;$('moodBadge').textContent=d.pos>d.neg?'Positive':'Mixed';$('moodBadge').className='badge '+(d.pos>d.neg?'pos':'neg');$('themes').innerHTML=d.themes.map((x,i)=>`<div class="topic"><div><div class="topic-name">${x}</div><div class="topic-meta">${(2200-i*310).toLocaleString()} mentions · ${i<2?'rising':'stable'}</div></div><span class="badge ${i<2?'pos':'neu'}">${i<2?'↑':'→'}</span></div>`).join('');$('alerts').innerHTML=d.alerts.map((x,i)=>`<div class="topic"><div><div class="topic-name">${x}</div><div class="topic-meta">${i===0?'High':'Medium'} confidence · updated just now</div></div><span class="badge ${i===0?'neg':'neu'}">${i===0?'Alert':'Info'}</span></div>`).join('');$('feed').innerHTML=makePosts(topic,d).join('');renderCharts(d);$('updated').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
    function makePosts(topic,d){const samples=[['AR','Analyst Radar',`Conversation around ${topic} is accelerating. Positive reactions are strongest among developers and product users.`, 'pos'],['VC','Venture Desk',`${topic} mentions are above the 7-day average, but the negative cluster is still limited to pricing and support issues.`, 'neu'],['MK','Market Watcher',`High engagement posts about ${topic} are moving faster than normal. Sentiment is constructive but needs monitoring.`, d.neg>20?'neg':'pos'],['PR','Product Pulse',`Users are sharing practical use-cases for ${topic}; creator commentary is pushing reach beyond the core tech audience.`, 'pos'],['CS','Customer Signal',`Support-related complaints for ${topic} are present but not yet driving the overall narrative.`, 'neu']];return samples.map(s=>`<article class="post"><div class="post-top"><div class="avatar">${s[0]}</div><div><b>${s[1]}</b><small>@${s[1].toLowerCase().replaceAll(' ','_')} · ${Math.floor(Math.random()*40+4)}m ago</small></div></div><p>${s[2]}</p><div class="post-foot"><span class="badge ${s[3]}">${s[3]==='pos'?'Positive':s[3]==='neg'?'Negative':'Neutral'}</span><span>♡ ${Math.floor(Math.random()*9000+900).toLocaleString()} · ↻ ${Math.floor(Math.random()*1900+120).toLocaleString()}</span></div></article>`)}
    $('trackBtn').addEventListener('click',()=>render($('topicInput').value.trim()||'OpenAI'));
    $('chips').addEventListener('click',e=>{if(!e.target.classList.contains('chip'))return;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));e.target.classList.add('active');$('topicInput').value=e.target.textContent;render(e.target.textContent)});
    render('OpenAI');setInterval(()=>{$('updated').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})},15000);